version: "3.6"

# This docker-compose file sets up the postgres container to listen for requests
# from your application. To make use of this, your application needs to be configured
# for a local environment to send data requests to http://postgres:5432 when executing
# from within the microservice-network in docker
#

services:
  postgres:
    image: postgres:11.7-alpine
    ports:
      - 5005:5432
    environment:
      POSTGRES_PASSWORD: supersecretpassword
networks:
  default:
    external:
      name: microservice-network
      # The network can be renamed to whatever you want
      # If you change this here, it also needs to be changed in the package.json scripts
      # in the "service" script and in the "dynamo:network" script.
      